# Generated by Django 4.1 on 2023-08-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppTwo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="lastname",
            new_name="last_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_email",
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.DeleteModel(
            name="UserEmail",
        ),
    ]
